# Generated by Django 4.1.3 on 2022-11-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="overspeed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("oid", models.IntegerField()),
                ("Create_Date", models.CharField(max_length=200)),
                ("Plat_Nomor", models.CharField(max_length=200)),
                ("Speed", models.CharField(max_length=200)),
                ("foto", models.CharField(max_length=200)),
                ("id_speed", models.CharField(max_length=200)),
                ("waktu", models.CharField(max_length=200)),
            ],
        ),
    ]
